### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/team-tasks#7]
Given Facebook's lawyers, we must change our name. Openspace was the determined one, now given the German conferencing software company OpenSpace-Online from 1999 is threatening legal action, we have to reconsider as we're consulted with lawyers and it's some 50/50 chance we get through or we get fined and loose TM in Germany.

**Comment by aquilesC** [comment]
Wait, what? Facebook is seriously threatening you because of the _book_ in your name?

**Comment by lifenautjoe** [comment]
Yep https://euipo.europa.eu/eSearch/#details/trademarks/018075708

**Comment by aquilesC** [comment]
It is very sad that things work this way! Basically, Facebook has claimed ownership of the word Book for everything which is not actually a _book_. 

> Software for making reservations and bookings

I wonder whether *Book*ing is OK with this... 

Anyways, Okuna is a good name! Keep it Up! :D
